### ISSUE TITLE
build passing

### ISSUE THREAD

**Issue by jp1017** [JackyAndroid/AndroidTVLauncher#1]
感谢分享！
看了下，没有.travis.yml
然后点击build passing
震惊了有木有，哈哈哈
:smiley:

**Comment by JackyAndroid** [comment]
@jp1017 多谢提醒     🙂

**Comment by jp1017** [comment]
？？？

**Comment by JackyAndroid** [comment]
@jp1017 稍后会把用travis-ci build过程同步上来
