### ISSUE TITLE
App页面的Fragment 中GridView无法向下滚动

### ISSUE THREAD

**Issue by tracyliu1** [JackyAndroid/AndroidTVLauncher#17]
com.jacky.compatible.launcher.features.app.AppFragment

  mGridView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {

```
            Log.e(TAG, "onItemClick");
            AppBean appBean = mAppList.get(position);
            Toast.makeText(mParent, "appBean = " + appBean.toString(), Toast.LENGTH_SHORT).show();

          //  runApp(appBean);
        }
    });
```

**Comment by htl1104** [comment]
请好,请问现在解决这个问题了嘛?

**Comment by JackyAndroid** [comment]
@htl1104 可以使用recyclerview替换gridview，在new item view里面requestfocus。最近没时间，你们如果修复了记得提交PR

**Comment by JackyAndroid** [comment]
考虑之后出一个仿乐视桌面的兼容低版本的桌面，旧桌面因各种问题已删除
