### ISSUE TITLE
博主在吗？

### ISSUE THREAD

**Issue by perk-jiang** [JackyAndroid/AndroidTVLauncher#20]
我在家里芒果tv上安装上去后，却使用不了，版本android 5.1，不知道为什么。。你有qq么，加号聊聊，我有个项目需求，咨询你的看法

**Comment by JackyAndroid** [comment]
@perk-jiang 如果自己先发现问题，请尽量自己查看log定位问题。如果不能定位问题或有疑问请把具体的问题和log贴出来，我只回答关于我的项目的疑问
