### ISSUE TITLE
Where can I download the apk?

### ISSUE THREAD

**Issue by qwIvan** [JackyAndroid/AndroidTVLauncher#21]
Or I have to build it manually

**Comment by qwIvan** [comment]
I found the old version...
http://www.wandoujia.com/apps/com.jacky.catlauncher
看来还是自己

**Comment by JackyAndroid** [comment]
@qwIvan 目前还没有放到市场上，只是作为一个技术项目，没有去运营

**Comment by solologo** [comment]
豌豆荚上的作者竟然是。。。。

**Comment by solologo** [comment]
我觉得作者有必要上架这个应用，，，以正视听，顺便打脸。

**Comment by qwIvan** [comment]
@solologo 我去，改名了

**Comment by sang54545454** [comment]
很想了解作者被抄袭后的感想

**Comment by es6china** [comment]
掘金看到的，加个星  关注一下

**Comment by yangleyou** [comment]
最近这个00后CEO怎么回事，应该是个炒作吧。

**Comment by JackyAndroid** [comment]
由于国内的电视应用市场过于混乱，而且国内上Google play 也很方便，现在Apk在fir.im上做分发，链接：https://fir.im/3yhj，以后等有机会再上市场
