### ISSUE TITLE
作者在崇才网络科技？

### ISSUE THREAD

**Issue by Loyea** [JackyAndroid/AndroidTVLauncher#22]
如题，在一个视频里面看到了这个作品 

http://www.cnbeta.com/articles/tech/648297.htm

**Comment by JackyAndroid** [comment]
@Loyea 我擦，要不是你提醒我还不知道呢，这是赤裸裸的拷贝啊

**Comment by jasonlam0619** [comment]
这也太不要脸了。

**Comment by wenmingtang** [comment]
火前留名

**Comment by zhangrui49** [comment]
马克一下

**Comment by mgfjxxiexiaolong** [comment]
围观

**Comment by phpdever** [comment]
作为一个00后，上学是不可能上学的，只有每天瞎BB，抄点小项目才能维持得了生活，网上的菜鸟又多，啥都不懂，我超喜欢这样的，老师叫我去办公室我都不去。

**Comment by XYScience** [comment]
根据Apache 2，得看那蛋蛋后有没有写上credit，否则才会侵权吧？不过那蛋蛋后连图片布局都不改，又不通知您本人，这道德上确实太垃圾了～～

**Comment by zibuyu1995** [comment]
围观，想问一下00后他的王者荣耀到什么段位了。。。

**Comment by Jayin** [comment]
## IT界哪有抄袭，只有参考(fork)

**Comment by WangChangQin** [comment]
这个也是666，图也不换

**Comment by af913337456** [comment]
留名

**Comment by XPGSnail** [comment]
求科普apache 2开源协议有啥要求

**Comment by MrZWH** [comment]
楼主慧眼如炬

**Comment by imknown** [comment]
```
License: GNU GPL v3.0
```
Copied from https://github.com/JackyAndroid/AndroidTVLauncher#license

**Comment by Lx91** [comment]
火钳留名

**Comment by aikongmeng** [comment]
转载不标明来源的都是流氓

**Comment by GHYOWEE** [comment]
火钳刘明  挺你哦作者

**Comment by ananas-xxj** [comment]
围观 很多00后喜欢呵呵，你们发现没

**Comment by aohanyao** [comment]
https://www.tianyancha.com/company/2316641157

**Comment by johnninja** [comment]
刘明

**Comment by fengqiangboy** [comment]
流明

**Comment by brileyhe** [comment]
已准备好小马扎

**Comment by JumiRay** [comment]
某蛋蛋后不顾反对,公然拷贝开源项目,弄虚作假，coder对此表示坚决反对并予强烈谴责 ---火钳留名

**Comment by lennyup** [comment]
火钳留名

**Comment by YogiAi** [comment]
火前留名...

**Comment by laobie** [comment]
![image](https://user-images.githubusercontent.com/7184320/30043604-e6800be2-922a-11e7-97a3-b3e088b87cfc.png)

**Comment by YY007H** [comment]
火钳留名

**Comment by osindex** [comment]
围观。

**Comment by SymphonyZhang** [comment]
已经坐在小马扎上了

**Comment by lpslpsl** [comment]
火钳留名。不过你之前是apache协议。不知道有没得用哦

**Comment by SymphonyZhang** [comment]
总感觉我们现在是给他炒热度。。。。。

**Comment by liuchong** [comment]
这是fork，不能算抄……fork……程序员的事，能算抄吗？

**Comment by JonathanLv** [comment]
围观。。。

**Comment by liuchong** [comment]
fork不能算抄……fork！……程序员的事，能算抄吗？

**Comment by AnyYANG** [comment]
哎，这个社会好浮躁。

**Comment by IceEnd** [comment]
怎么说呢，至少将项目名字改了，也算得上抄袭的进步吧。

**Comment by huuohao** [comment]
他还是个孩子 一定要打死

**Comment by laosijidididi** [comment]
火钳留名

**Comment by tuzixiansheng** [comment]
emmmmmmmn火钳

**Comment by nexus943312912** [comment]
了不得

**Comment by shiguiyou** [comment]
不得了

**Comment by GuaiYiHu** [comment]
mark

**Comment by TimmyGzw** [comment]
围观

**Comment by LiuXi0314** [comment]
围观围观
```````

**Comment by xiaoyucoding** [comment]
火钳

**Comment by dugutianxue** [comment]
支持作者维权~~ 他不收协议在先~~不知道在国内可否直接起诉~~~

**Comment by chriiess** [comment]
火钳刘明，小马扎已就位

**Comment by nbcallum** [comment]
支持作者起诉，给他脸了

**Comment by GinRyan** [comment]
一般来说作者都是把整个完整的可运行的项目作为GPL许可开源，库项目以及框架使用Apache许可开源，再就是更加品德高古的是用MIT或者BSD许可开源，基本都是以人作为服务主体。但是无视许可这件事，从品德上就说不过去，所以，作者把开源项目许可修改为GPL是明智之举。
在韩国，GPL侵权已有法院判决的先例：[http://www.solidot.org/story?sid=52389](Solidot)。

**Comment by EdiTurn** [comment]
只是在演示视频里出现了，APP 都没有分发何来侵权，即便用 GPL 也是如此，更何况 Apache……
开源并不是潮流，如果对于别人拿你的东西赚钱感到不舒服，那还是闭源或选择更严格的许可证为好。

**Comment by ooozbh** [comment]
火钳流明这00后简直就是个程序员翻版tf boys

**Comment by xcatliu** [comment]
支持作者起诉。
新闻中有截图，雷军鼓励了他创业。可以发微博 @雷军 说明是抄袭的

**Comment by xujinliang** [comment]
起诉就是笑话，跟1个10几岁的小娃娃较劲？算了，他们也只是拷贝，没有能力修改的，作者心放宽，他们间接帮助你的软件出名了

**Comment by yangnk** [comment]
感觉也用不着和小孩较什么劲，抱着看小朋友过家家的心态吧～

**Comment by BolexLiu** [comment]
对于抄袭这种事好与不好不做评论，因为他还是一个未成年。
我17岁那年可没那么厉害，好像现在也没有。😢

但是反观给我的是，我容易妄加揣测的认为背后会有投资人来利用它。


----广告时间----
蹭一个热点顺便打小广告。
https://github.com/BolexLiu/ReciteWords
一个IntelliJ IDEA、Android Studio 记单词翻译插件,可以将英文翻译为中文并记录到生词本提供查阅。

**Comment by kehao95** [comment]
放心吧，他这也就是跑起来演示一下。这家伙肯定没有能力修改，甚至我怀疑能不能建个网站进行分发……

**Comment by yongyu0102** [comment]
![dmm aoafq ovb 9 o s a5](https://user-images.githubusercontent.com/13392987/30046480-af1d8680-923d-11e7-8baa-bc65779eb11a.png)
对于这些 30 多岁的老程序员，他们对互联网不了解， fork 是这么用的？

**Comment by sfyc23** [comment]
支持一下作者。

**Comment by huxiaotian123** [comment]
围观

**Comment by songhaoreact** [comment]
围观

**Comment by tracy1989wan** [comment]
支持原作者

**Comment by huxizhijian** [comment]
战略性mark一下

**Comment by tianqiujie** [comment]
战略性mark一下

**Comment by loveincode** [comment]
作者你也出名了。

**Comment by lzsheng** [comment]
支持正版！

**Comment by danielqsj** [comment]
mark

**Comment by deimo** [comment]
githup观光团

**Comment by litmus4** [comment]
微博观光团 666

**Comment by litmus4** [comment]
微博观光团 666，支持作者维权

**Comment by JustinLance** [comment]
火一把

**Comment by hfkai** [comment]
作者屌他！！！不能就这么算了，这侵权行为！！！

**Comment by fengtianxiang** [comment]
战略性mark一下

**Comment by kn007** [comment]
国内开源环境堪忧。

**Comment by snowdream** [comment]
关注

**Comment by razerdp** [comment]
火前留名

**Comment by Norman300** [comment]
不得了 不得了

**Comment by 1120054743** [comment]
我也留个名。

**Comment by skywalkerhbz** [comment]
专门去看了一下采访这位00后ceo的视频，说话的语气那真的是。。。太JB恶心

**Comment by junyuzhu** [comment]
打个酱油～～！

**Comment by timelessg** [comment]
小时偷针 长大偷金

**Comment by acmerli** [comment]
看了那个采访视频就感觉不对  果然是抄的。不过Apache算是个比较宽松的协议 不过就这样直接copy过去也太不道德了

**Comment by teekie** [comment]
我其实更感慨的是国内媒体的素质，总想搞个大新闻

**Comment by chrisArthas** [comment]
围观围观

**Comment by DesignQu** [comment]
掘金过来的~

**Comment by PiPiCaptain** [comment]
给个转账二维码，我们coder众筹一波，让你去告死他 @JackyAndroid

**Comment by DesignQu** [comment]
这是这小子的微博http://weibo.com/u/1795018287?refer_flag=1001030102_&is_hot=1

**Comment by uselessaddress** [comment]
简介里有：
> sunshine女团独立营销人
23333

**Comment by ToyoDAdoubi** [comment]
火钳刘明 :rofl:

**Comment by keys961** [comment]
留名围观

**Comment by NeilRen** [comment]
火钳刘明，小马扎已准备好，瓜子也买上了

**Comment by lauixData** [comment]
留名，支持告他。

**Comment by johnninja** [comment]
@yongyu0102 蛋蛋后自认了解互联网，我只想问：在浏览器输入URL回撤之后都发生了什么？😏

**Comment by NeilRen** [comment]
@johnninja 蛋蛋：URL 是什么？

**Comment by johnninja** [comment]
@NeilRen 好吧，我承认是网址😂

**Comment by xiaolongyuan** [comment]
+1
http://www.oschina.net/news/88407/open-source-software-copied

**Comment by lizixian18** [comment]
刚在头条看到新闻了，厉害了，过来蹭一下热度。

**Comment by xiaoqib** [comment]
还是00后 社会啊

**Comment by Bianfuchen** [comment]
然而又有什么办法？又没有相关的法律规定和惩罚条例。只能谴责。他或许以为开源就可以不打招呼，商业化。

**Comment by RealOuO** [comment]
蛋蛋后，蛋蛋疼，fork一发

**Comment by DesignQu** [comment]
这里成聊天室了。。。

**Comment by yygutn** [comment]
火钳刘明

**Comment by ushuaia** [comment]
围观

**Comment by yongyu0102** [comment]
@johnninja  
![cy 3l87i mqg1 bb80t dxc](https://user-images.githubusercontent.com/13392987/30053747-6f3ea444-925c-11e7-9ebc-b200959e35b8.jpg)

**Comment by johnninja** [comment]
@yongyu0102 我靠你这胖虎满屏了，我看你就是在刁难我😂

**Comment by yongyu0102** [comment]
@johnninja  
![4k lv _a qv3zgfs vyood](https://user-images.githubusercontent.com/13392987/30054004-3a0b55d2-925d-11e7-8342-87bc1c908ed7.jpg)
 不敢不敢

**Comment by jenkey2011** [comment]
关注

**Comment by Loyea** [comment]
所谓的无心插柳柳成荫就是这种感觉吧。。。。活了20几年，没想到随便一句话竟然上了新闻😅

罢了罢了，事了拂衣去，深藏功与名。/滑稽

**Comment by johnninja** [comment]
@Loyea 活捉闹事主谋！/滑稽

**Comment by zeroonechange** [comment]
github本就是开源的   这点作者你怎么看? @Loyea

**Comment by Loyea** [comment]
@zeroonechange  我不是作者啊😅

**Comment by peasshoter** [comment]
蹭蹭

**Comment by ananas-xxj** [comment]
这是要笑死我啊 @Loyea :sweat_smile:

**Comment by shangyifei** [comment]
啊啊啊

**Comment by pigdu** [comment]
我要把git上所有项目都fork一下，然后去当个CEO去！

·············CEO是啥啊~？~

**Comment by starktonys** [comment]
起诉就是笑话，跟1个10几岁的小娃娃较劲？算了，他们也只是拷贝，没有能力修改的，作者心放宽，他们间接帮助你的软件出名了

**Comment by jyfmidi** [comment]
留名

**Comment by JackyAndroid** [comment]
事情到此为止。
曝光目的有二：
1. 让大家清楚这个人的为人。
2. 提高大家的版权意识。

最近我会把产品进行整理，发布到应用市场。

**Comment by JreeyButler** [comment]
留名，关注

**Comment by greedyhao** [comment]
关注

**Comment by qwIvan** [comment]
#21 所以什么时候给我build最新版的apk:joy:

**Comment by paperbag** [comment]
> github本就是开源的 这点作者你怎么看?

开源≠没有版权，请不要混淆概念。 @zeroonechange

**Comment by xxxgitone** [comment]
支持维权！等待新进展

**Comment by XH888** [comment]
火钳刘明。哈哈哈呵呵呵

**Comment by tuzixiansheng** [comment]
就算老一辈企业家不懂互联网，至少他们懂得fork

**Comment by imnotpopo** [comment]
围观

**Comment by liubiqu** [comment]
支持作者

**Comment by wynnfynn** [comment]
趁他小别放过他,等到发展到X讯辣么大,老一辈企业家真就不懂互联网了,后面300勇士呢

**Comment by xpoll** [comment]
支持作者维权~~

**Comment by veryrich** [comment]
特来支持作者维权，话说我7刀一个库看来花的值了~~

**Comment by laishujie** [comment]
支持作者

**Comment by Jiuyong** [comment]
他还是个孩子，所以要拯救他！
不但要拯救他一个，还要拯救千千万万像他这样努力的孩子！
支持作者，为了下一代，一定要维权！

**Comment by vincenth520** [comment]
刘明

**Comment by bhui** [comment]
他还是个孩子啊!抛开自身所受的教育和经历不说，父母家庭的责任也不可推卸

**Comment by hantsy** [comment]
@bhui 你想得太简单了，中国这种大环境，一个小孩子这么张扬，背后肯定有人（可能就是他们父母）推的。这和湖南台的那些选秀节目一样，早有人在背后操盘。

**Comment by Rsplwe** [comment]
支持作者，作为开发者抄袭源码是可耻的，关键是他们根本算不上开发者。

**Comment by fakefred** [comment]
不要和沒B數的人瞎計較。
直接上微博熱搜，肝死他。
