### ISSUE TITLE
这个项目已经 Github 热门第五了，兄弟们加油

### ISSUE THREAD

**Issue by QuincySx** [JackyAndroid/AndroidTVLauncher#24]

**Comment by JustinLance** [comment]
逆天了 。。。。

**Comment by QuincySx** [comment]
![image](https://user-images.githubusercontent.com/13297229/30051679-85103c58-9255-11e7-9f0b-dba22222810c.png)
Java版区第二厉害了

**Comment by Loser-XiaoZhi** [comment]
无敌了！！

**Comment by viakiba** [comment]
火钳留名

**Comment by xiaolongyuan** [comment]
+1

**Comment by haoyunZhou** [comment]
笑笑。。。

**Comment by solologo** [comment]
伸手党来了，，有没有编译好的apk...

**Comment by JackyAndroid** [comment]
事情到此为止。
曝光目的有二：
1. 让大家清楚这个人的为人。
2. 提高大家的版权意识。

最近我会把产品进行整理，发布到应用市场。
