### ISSUE TITLE
看到新闻过来的，支持作者维权, 请在目录里提供GPL的全文或链接

### ISSUE THREAD

**Issue by ryh** [JackyAndroid/AndroidTVLauncher#27]
支持作者维权

但GPL好像必须提供全文或者连接

>  You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

**Comment by qwIvan** [comment]
现在加GPL的话，意味着从现在的版本开始不能被盗用代码，人家只要用你以前的版本就行了。。。

**Comment by Lt-grint** [comment]
关于GPL协议太了解的可以看看这个，https://www.oschina.net/question/12_2826

**Comment by JackyAndroid** [comment]
已加。
