### ISSUE TITLE
看新闻什么首位00后CEO，现在才知道原来是这样啊！支持作者维权！！！

### ISSUE THREAD

**Issue by zhenqicai** [JackyAndroid/AndroidTVLauncher#28]
开源项目是做为大家进行学习研究的，而有些人竟拿去换取利益！你抄袭就抄袭吧，至少抄袭的与原创不能雷同吧，而这位号称首位00后，直接将这项目拿过来，然后对媒体说是自己开发的产品，对于这种人我们深恶痛绝，不便多说什么！

**Comment by QuantumLiu** [comment]
作者是gpl协议，理论上来说那位CEO只要开源自己的项目，怎么用都随便

**Comment by qwIvan** [comment]
@QuantumLiu 是今天才改的GPL，提前的版本是阿帕奇

**Comment by Lensual** [comment]
支持作者维权，反对抄袭开源作品。
（火钳刘明

**Comment by ze00** [comment]
GPL也好Apache也好，反正人家都不会理(

**Comment by sang54545454** [comment]
首位00后CEO不过如此嘛   雷军打脸不？

**Comment by steambap** [comment]
他还是一个孩纸，我们不要放过他。

**Comment by xuchenchen** [comment]
程序猿辛辛苦苦的写代码容易吗？这个00后直接拿来说是自己的还炫耀，是不是我把谷歌的开源都下载下来我就是下一个500强啊哈哈

**Comment by johnninja** [comment]
大家都散了吧！作者已经给出解释，通过此事加强大家的版权意识。而且知乎上看蛋蛋后弄过很多这种事，直接拿过别人的开源项目，改一改包名，就当自己的了。😂

**Comment by JackyAndroid** [comment]
事情到此为止吧
