### ISSUE TITLE
崇才科技拿走的那个桌面app么？

### ISSUE THREAD

**Issue by MrXionGe** [JackyAndroid/AndroidTVLauncher#30]

**Comment by JackyAndroid** [comment]
是，这件事情已经结束了

**Comment by wsdjeg** [comment]
这件事情在网上传的沸沸扬扬，可结果却是莫名其妙，最终如何解决？这边一直没有明说，或者抄袭者对此事的态度，我觉得作者应该公示出来。给我的感觉这种就像是一种非常上不了台面的营销手段！

**Comment by JackyAndroid** [comment]
@wsdjeg 
1. 这件事情更多是道德问题
2. 我在文章里目的已经说明，只是为了谴责这种行为
3. 现在目的已经达到，事情自然就过去了

**Comment by MrXionGe** [comment]
@JackyAndroid 
没记错的话，您换了开源协议

**Comment by JackyAndroid** [comment]
@MrXionGe 换协议有什么问题吗？
