### ISSUE TITLE
無法正常顯示

### ISSUE THREAD

**Issue by tenSunFree** [JackyAndroid/AndroidTVLauncher#31]
![2017-09-12_134345](https://user-images.githubusercontent.com/23090085/30310026-f7162928-97c0-11e7-9d7e-640d7248a002.jpg)
![2017-09-12_134411](https://user-images.githubusercontent.com/23090085/30310025-f715b1be-97c0-11e7-95f1-b011c8bf900f.jpg)

不知道是不是因為手機版型的關係, 導致顯示上面出了問題?
我應該怎麼解決這個問題?

**Comment by JackyAndroid** [comment]
这个应用是适配tv的，其他设备不兼容
