### ISSUE TITLE
Unable to compile, since a couple of API changes are made

### ISSUE THREAD

**Issue by TetrisSQC** [JackyAndroid/AndroidTVLauncher#36]
Is there a chance that you update the project in order to work with the latest glide build?

Cheers

**Comment by JackyAndroid** [comment]
I will do this when I take time.

**Comment by JackyAndroid** [comment]
Has been upgraded to api27

**Comment by JackyAndroid** [comment]
Refer to the official migration plan for the Glide upgrade：https://muyangmin.github.io/glide-docs-cn/doc/migrating.html
