### ISSUE TITLE
can't install the apk

### ISSUE THREAD

**Issue by niccolobusato** [JackyAndroid/AndroidTVLauncher#42]
i've downloaded your apk from releases tab. when trying to install give me an error: App not installed - "the app cloud be damaged". any help?

**Comment by JackyAndroid** [comment]
redownload or build apk from the source.

**Comment by FivePixels** [comment]
Also having this issue - could you provide instructions for building the APK? @JackyAndroid

**Comment by JackyAndroid** [comment]
@FivePixels Are you a developer？

**Comment by FivePixels** [comment]
> @FivePixels Are you a developer？If not, try downloading it from the release tab

I got it working by passing the -t flag during my install through adb.
