### ISSUE TITLE
无法安装apk，提示“该软件包似乎已损坏。”

### ISSUE THREAD

**Issue by Sonic853** [JackyAndroid/AndroidTVLauncher#43]
设备：斐讯T1、小米Max

安卓版本：7.1.2

应用版本：2.1

复现方法：
从releases里下载，点击下载后的apk安装提示损坏。
使用mt重新签名后重试安装也提示损坏。

**Comment by JackyAndroid** [comment]
https://github.com/JackyAndroid/AndroidTVLauncher/releases/tag/2.1
再试下

**Comment by Sonic853** [comment]
> https://github.com/JackyAndroid/AndroidTVLauncher/releases/tag/2.1
> 再试下

用这两个设备重新试了下，还是提示“该软件包似乎已损坏。”
（然后使用安卓5.1.1的夜神模拟器测试安装也同样安装不上。。orz

**Comment by JackyAndroid** [comment]
那自己用源码build apk吧

**Comment by ZhuSky** [comment]
adb 安装提示
Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]

**Comment by Sonic853** [comment]
> INSTALL_FAILED_TEST_ONLY: installPackageLI

这个错误有试过在百度上找吗？[https://blog.csdn.net/jianiao/article/details/86476737](https://blog.csdn.net/jianiao/article/details/86476737)
