### ISSUE TITLE
2 issues 

### ISSUE THREAD

**Issue by panicattack95** [JackyAndroid/AndroidTVLauncher#47]
- navigation up or down sometimes stops working after going back to the home screen after quiting an app
- on the Home Screen at the bottom, the gaming controller icon is low-resolution and blurry

**Comment by achmadsutardi441953** [comment]
![Screenshot_20210714_121122](https://user-images.githubusercontent.com/30205044/125565051-fc7997b3-8c65-42d4-a817-470a83348e30.jpg)
App Not installed

**Comment by JackyAndroid** [comment]
Not suitable for mobile phone
