### ISSUE TITLE
下载Demo,打开AS,直接使用as电视模拟器,为什么跑步起来呀?

### ISSUE THREAD

**Issue by ILoveLin** [JackyAndroid/AndroidTVLauncher#49]
> Task :app:mergeLibDexDebug UP-TO-DATE
> Task :app:dexBuilderDebug UP-TO-DATE
> Task :app:mergeProjectDexDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :app:mergeDebugNativeLibs UP-TO-DATE
> Task :app:stripDebugDebugSymbols UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:packageDebug UP-TO-DATE
> Task :app:assembleDebug UP-TO-DATE

BUILD SUCCESSFUL in 1s
26 actionable tasks: 26 up-to-date

Build Analyzer results available

运行只有这一串编译代码!

**Comment by JackyAndroid** [comment]
不适配模拟器

**Comment by ILoveLin** [comment]
好的谢谢大佬~
